[build]
  command = "flutter clean && flutter pub get && flutter build web --release"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ปรับแต่งการตั้งค่า cache-control
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# สำหรับไฟล์ JavaScript
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
  
[build.environment]
  FLUTTER_CHANNEL = "stable"
  FLUTTER_VERSION = "3.29.0"
